// This file is auto-generated by fetch-all-logos.js
// Run 'npm run fetch-logos' periodically to update this list with new integrations
// Last updated: 2025-11-07T16:27:41.977Z

export const logos = [
    {
        "slug": "1password",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/1password/img/1password-logo-light-bg.svg"
    },
    {
        "slug": "abnormal_security",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/abnormal_security/img/abnormal-security-logo-dark.svg"
    },
    {
        "slug": "activemq",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/activemq/img/activemq.svg"
    },
    {
        "slug": "admin_by_request_epm",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/admin_by_request_epm/img/logo.svg"
    },
    {
        "slug": "airflow",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/airflow/img/airflow.svg"
    },
    {
        "slug": "airlock_digital",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/airlock_digital/img/airlock_digital-logo.svg"
    },
    {
        "slug": "akamai",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/akamai/img/akamai_logo.svg"
    },
    {
        "slug": "amazon_s3",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/elastic_connectors/img/service_type/amazon_s3.svg"
    },
    {
        "slug": "amazon_security_lake",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/amazon_security_lake/img/amazon-security-lake-logo.svg"
    },
    {
        "slug": "apache",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/apache/img/logo_apache.svg"
    },
    {
        "slug": "apache_otel",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/apache_otel/img/logo_apache.svg"
    },
    {
        "slug": "apache_spark",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/apache_spark/img/apache_spark-logo.svg"
    },
    {
        "slug": "apache_tomcat",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/apache_tomcat/img/logo.svg"
    },
    {
        "slug": "apm",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/apm/img/logo_apm.svg"
    },
    {
        "slug": "arista_ngfw",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/arista_ngfw/img/arista-logo.svg"
    },
    {
        "slug": "armis",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/armis/img/armis-logo.svg"
    },
    {
        "slug": "atlassian_bitbucket",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/atlassian_bitbucket/img/bitbucket-logo.svg"
    },
    {
        "slug": "atlassian_confluence",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/atlassian_confluence/img/confluence-logo.svg"
    },
    {
        "slug": "atlassian_jira",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/atlassian_jira/img/jira-software-logo.svg"
    },
    {
        "slug": "auditd",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/auditd/img/linux.svg"
    },
    {
        "slug": "auditd_manager",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/auditd_manager/img/linux.svg"
    },
    {
        "slug": "auth0",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/auth0/img/auth0-logo.svg"
    },
    {
        "slug": "authentik",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/authentik/img/authentik-logo.svg"
    },
    {
        "slug": "aws",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/aws/img/logo-aws-config.svg"
    },
    {
        "slug": "aws_bedrock",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/aws_bedrock/img/icon.svg"
    },
    {
        "slug": "aws_billing",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/aws_billing/img/logo_aws.svg"
    },
    {
        "slug": "aws_elb_otel",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/aws_elb_otel/img/logo.svg"
    },
    {
        "slug": "aws_logs",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/aws_logs/img/icon.svg"
    },
    {
        "slug": "aws_mq",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/aws_mq/img/aws-mq-logo.svg"
    },
    {
        "slug": "aws_vpcflow_otel",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/aws_vpcflow_otel/img/icon.svg"
    },
    {
        "slug": "awsfargate",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/awsfargate/img/logo_fargate.svg"
    },
    {
        "slug": "awsfirehose",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/awsfirehose/img/logo_firehose.svg"
    },
    {
        "slug": "azure",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/azure/img/application_gateway_logo.svg"
    },
    {
        "slug": "azure_ai_foundry",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/azure_ai_foundry/img/ai_foundry.png"
    },
    {
        "slug": "azure_app_service",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/azure_app_service/img/app-service-logo.svg"
    },
    {
        "slug": "azure_application_insights",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/azure_application_insights/img/app_insights.png"
    },
    {
        "slug": "azure_billing",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/azure_billing/img/azure-billing-overview.png"
    },
    {
        "slug": "azure_blob_storage",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/azure_blob_storage/img/icon.svg"
    },
    {
        "slug": "azure_blob_storage",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/elastic_connectors/img/service_type/azure_blob_storage.svg"
    },
    {
        "slug": "azure_frontdoor",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/azure_frontdoor/img/front-door.svg"
    },
    {
        "slug": "azure_functions",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/azure_functions/img/azure-functions-icon.svg"
    },
    {
        "slug": "azure_logs",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/azure_logs/img/icon.svg"
    },
    {
        "slug": "azure_metrics",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/azure_metrics/img/azure_metrics_logo.png"
    },
    {
        "slug": "azure_network_watcher_nsg",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/azure_network_watcher_nsg/img/azure_network_watcher_logo.svg"
    },
    {
        "slug": "azure_network_watcher_vnet",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/azure_network_watcher_vnet/img/azure_network_watcher_logo.svg"
    },
    {
        "slug": "azure_openai",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/azure_openai/img/azure_open_ai_billing.png"
    },
    {
        "slug": "barracuda",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/barracuda/img/logo.svg"
    },
    {
        "slug": "barracuda_cloudgen_firewall",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/barracuda_cloudgen_firewall/img/logo.svg"
    },
    {
        "slug": "bbot",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/bbot/img/BlackLantern-LOGO.svg"
    },
    {
        "slug": "beaconing",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/beaconing/img/icon-machine-learning.svg"
    },
    {
        "slug": "beat",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/beat/img/logo_beat.svg"
    },
    {
        "slug": "beelzebub",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/beelzebub/img/beelzebub.svg"
    },
    {
        "slug": "beyondinsight_password_safe",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/beyondinsight_password_safe/img/logo.svg"
    },
    {
        "slug": "beyondtrust_pra",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/beyondtrust_pra/img/beyondtrust_pra-logo.png"
    },
    {
        "slug": "bitdefender",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/bitdefender/img/bitdefender_gravityzone.svg"
    },
    {
        "slug": "bitwarden",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/bitwarden/img/bitwarden-logo.svg"
    },
    {
        "slug": "blacklens",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/blacklens/img/blacklens-logo.svg"
    },
    {
        "slug": "box",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/elastic_connectors/img/service_type/box.svg"
    },
    {
        "slug": "box_events",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/box_events/img/box.svg"
    },
    {
        "slug": "canva",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/canva/img/canva-logo.svg"
    },
    {
        "slug": "carbon_black_cloud",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/carbon_black_cloud/img/carbon_black_cloud-logo.svg"
    },
    {
        "slug": "carbonblack_edr",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/carbonblack_edr/img/carbon-black-logo.svg"
    },
    {
        "slug": "cassandra",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/cassandra/img/cassandra.svg"
    },
    {
        "slug": "ceph",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/ceph/img/ceph-logo.svg"
    },
    {
        "slug": "checkpoint",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/checkpoint/img/checkpoint-logo.svg"
    },
    {
        "slug": "checkpoint_email",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/checkpoint_email/img/checkpoint-logo.svg"
    },
    {
        "slug": "checkpoint_harmony_endpoint",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/checkpoint_harmony_endpoint/img/checkpoint-logo.svg"
    },
    {
        "slug": "cisa_kevs",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/cisa_kevs/img/icon-threat-detection-64-color.svg"
    },
    {
        "slug": "cisco_aironet",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/cisco_aironet/img/cisco.svg"
    },
    {
        "slug": "cisco_asa",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/cisco_asa/img/cisco.svg"
    },
    {
        "slug": "cisco_duo",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/cisco_duo/img/cisco_duo-logo.svg"
    },
    {
        "slug": "cisco_ftd",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/cisco_ftd/img/cisco.svg"
    },
    {
        "slug": "cisco_ios",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/cisco_ios/img/cisco.svg"
    },
    {
        "slug": "cisco_ise",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/cisco_ise/img/cisco-ise-logo.svg"
    },
    {
        "slug": "cisco_meraki",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/cisco_meraki/img/cisco-logo.svg"
    },
    {
        "slug": "cisco_meraki_metrics",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/cisco_meraki_metrics/img/cisco-logo.svg"
    },
    {
        "slug": "cisco_nexus",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/cisco_nexus/img/cisco.svg"
    },
    {
        "slug": "cisco_secure_email_gateway",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/cisco_secure_email_gateway/img/cisco-logo.svg"
    },
    {
        "slug": "cisco_secure_endpoint",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/cisco_secure_endpoint/img/cisco.svg"
    },
    {
        "slug": "cisco_umbrella",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/cisco_umbrella/img/cisco.svg"
    },
    {
        "slug": "citrix_adc",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/citrix_adc/img/citrix_adc-logo.svg"
    },
    {
        "slug": "citrix_waf",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/citrix_waf/img/Citrix_Systems_logo.svg"
    },
    {
        "slug": "claroty_ctd",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/claroty_ctd/img/claroty-ctd-logo.svg"
    },
    {
        "slug": "claroty_xdome",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/claroty_xdome/img/claroty-xdome-logo.svg"
    },
    {
        "slug": "cloud_asset_inventory",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/cloud_asset_inventory/img/logo_cloud_security_posture.svg"
    },
    {
        "slug": "cloud_defend",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/cloud_defend/img/logo.svg"
    },
    {
        "slug": "cloud_security_posture",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/cloud_security_posture/img/logo_cloud_security_posture.svg"
    },
    {
        "slug": "cloudflare",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/cloudflare/img/cf-logo-v.svg"
    },
    {
        "slug": "cloudflare_logpush",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/cloudflare_logpush/img/cloudflare-logo.svg"
    },
    {
        "slug": "cockroachdb",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/cockroachdb/img/cockroachdb-overview.png"
    },
    {
        "slug": "confluence",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/elastic_connectors/img/service_type/confluence.svg"
    },
    {
        "slug": "containerd",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/containerd/img/containerd-logo.svg"
    },
    {
        "slug": "coredns",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/coredns/img/coredns-logo.svg"
    },
    {
        "slug": "corelight",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/corelight/img/corelight-logo.svg"
    },
    {
        "slug": "couchbase",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/couchbase/img/couchbase-logo.svg"
    },
    {
        "slug": "couchdb",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/couchdb/img/couchdb.svg"
    },
    {
        "slug": "cribl",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/cribl/img/logo.svg"
    },
    {
        "slug": "crowdstrike",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/crowdstrike/img/logo-integrations-crowdstrike.svg"
    },
    {
        "slug": "cyberark_epm",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/cyberark_epm/img/cyberark-logo.svg"
    },
    {
        "slug": "cyberark_pta",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/cyberark_pta/img/logo.svg"
    },
    {
        "slug": "cyberarkpas",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/cyberarkpas/img/logo.svg"
    },
    {
        "slug": "cybereason",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/cybereason/img/cybereason-logo.svg"
    },
    {
        "slug": "cyera",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/cyera/img/cyera-logo.svg"
    },
    {
        "slug": "cylance",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/cylance/img/logo.svg"
    },
    {
        "slug": "darktrace",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/darktrace/img/darktrace-logo.svg"
    },
    {
        "slug": "ded",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/ded/img/ded_Icon.svg"
    },
    {
        "slug": "dga",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/dga/img/icon-machine-learning.svg"
    },
    {
        "slug": "digital_guardian",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/digital_guardian/img/digital-guardian-logo.svg"
    },
    {
        "slug": "docker",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/docker/img/logo_docker.svg"
    },
    {
        "slug": "docker_otel",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/docker_otel/img/docker_logo.svg"
    },
    {
        "slug": "dropbox",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/elastic_connectors/img/service_type/dropbox.svg"
    },
    {
        "slug": "elastic_agent",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/elastic_agent/img/logo_elastic_agent.svg"
    },
    {
        "slug": "elastic_connectors",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/elastic_connectors/img/connectors-logo.svg"
    },
    {
        "slug": "elastic_package_registry",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/elastic_package_registry/img/elastic_package_registry-logo.svg"
    },
    {
        "slug": "elastic_security",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/elastic_security/img/elastic-security-logo.svg"
    },
    {
        "slug": "elasticsearch",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/elasticsearch/img/logo_elasticsearch.svg"
    },
    {
        "slug": "endace",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/endace/img/endace-logo.svg"
    },
    {
        "slug": "enterprisesearch",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/enterprisesearch/img/logo_entsearch.svg"
    },
    {
        "slug": "entityanalytics_ad",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/entityanalytics_ad/img/logo.svg"
    },
    {
        "slug": "entityanalytics_entra_id",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/entityanalytics_entra_id/img/logo-azure.svg"
    },
    {
        "slug": "entityanalytics_okta",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/entityanalytics_okta/img/okta-logo-dark.svg"
    },
    {
        "slug": "entro",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/entro/img/entro_security-logo.svg"
    },
    {
        "slug": "envoyproxy",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/envoyproxy/img/envoy.svg"
    },
    {
        "slug": "eset_protect",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/eset_protect/img/eset-protect-logo.svg"
    },
    {
        "slug": "ess_billing",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/ess_billing/img/sample-logo.svg"
    },
    {
        "slug": "etcd",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/etcd/img/etcd.svg"
    },
    {
        "slug": "extrahop",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/extrahop/img/extrahop-logo.svg"
    },
    {
        "slug": "f5_bigip",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/f5_bigip/img/f5-bigip-logo.svg"
    },
    {
        "slug": "falco",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/falco/img/falco-stacked-color.svg"
    },
    {
        "slug": "filestream",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/filestream/img/icon.svg"
    },
    {
        "slug": "fim",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/fim/img/sample-logo.svg"
    },
    {
        "slug": "fireeye",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/fireeye/img/FireEye-logo.svg"
    },
    {
        "slug": "first_epss",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/first_epss/img/first-org-RGB.svg"
    },
    {
        "slug": "fleet_server",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/fleet_server/img/logo_fleet_server.svg"
    },
    {
        "slug": "forcepoint_web",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/forcepoint_web/img/forcepoint.svg"
    },
    {
        "slug": "forgerock",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/forgerock/img/forgerock-icon.svg"
    },
    {
        "slug": "fortinet_forticlient",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/fortinet_forticlient/img/fortinet-logo.svg"
    },
    {
        "slug": "fortinet_fortiedr",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/fortinet_fortiedr/img/fortinet-logo.svg"
    },
    {
        "slug": "fortinet_fortigate",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/fortinet_fortigate/img/fortinet-logo.svg"
    },
    {
        "slug": "fortinet_fortimail",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/fortinet_fortimail/img/fortinet-logo.svg"
    },
    {
        "slug": "fortinet_fortimanager",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/fortinet_fortimanager/img/fortinet-logo.svg"
    },
    {
        "slug": "fortinet_fortiproxy",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/fortinet_fortiproxy/img/fortinet-logo.svg"
    },
    {
        "slug": "gcp",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/gcp/img/logo_gcp.svg"
    },
    {
        "slug": "gcp_metrics",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/gcp_metrics/img/logo_gcp.svg"
    },
    {
        "slug": "gcp_pubsub",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/gcp_pubsub/img/logo_gcp.svg"
    },
    {
        "slug": "gcp_vertexai",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/gcp_vertexai/img/gcp_vertexai.svg"
    },
    {
        "slug": "gigamon",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/gigamon/img/gigamon-logo.svg"
    },
    {
        "slug": "github",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/github/img/github.svg"
    },
    {
        "slug": "github",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/elastic_connectors/img/service_type/github.svg"
    },
    {
        "slug": "gitlab",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/gitlab/img/gitlab-logo.svg"
    },
    {
        "slug": "gmail",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/elastic_connectors/img/service_type/gmail.svg"
    },
    {
        "slug": "goflow2",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/goflow2/img/goflow2-logo.svg"
    },
    {
        "slug": "golang",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/golang/img/golang-logo.svg"
    },
    {
        "slug": "google_cloud_storage",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/google_cloud_storage/img/icon.svg"
    },
    {
        "slug": "google_cloud_storage",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/elastic_connectors/img/service_type/google_cloud_storage.svg"
    },
    {
        "slug": "google_drive",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/elastic_connectors/img/service_type/google_drive.svg"
    },
    {
        "slug": "google_scc",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/google_scc/img/google-scc-logo.svg"
    },
    {
        "slug": "google_secops",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/google_secops/img/google-secops-logo-with-text.svg"
    },
    {
        "slug": "google_workspace",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/google_workspace/img/logo.svg"
    },
    {
        "slug": "hadoop",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/hadoop/img/hadoop-logo.svg"
    },
    {
        "slug": "haproxy",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/haproxy/img/logo_haproxy.svg"
    },
    {
        "slug": "hashicorp_vault",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/hashicorp_vault/img/Vault_VerticalLogo_Color_RGB.svg"
    },
    {
        "slug": "hid_bravura_monitor",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/hid_bravura_monitor/img/logo_hid_bravura_monitor.svg"
    },
    {
        "slug": "hpe_aruba_cx",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/hpe_aruba_cx/img/aruba-networks-logo.svg"
    },
    {
        "slug": "hta",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/hta/img/security-logo-color-64px.svg"
    },
    {
        "slug": "http_endpoint",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/http_endpoint/img/icon.svg"
    },
    {
        "slug": "ibm_qradar",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/ibm_qradar/img/ibm_qradar-logo.svg"
    },
    {
        "slug": "ibmmq",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/ibmmq/img/ibmmq.svg"
    },
    {
        "slug": "iis",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/iis/img/iis.svg"
    },
    {
        "slug": "iis_otel",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/iis_otel/img/iis_otel.svg"
    },
    {
        "slug": "imperva",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/imperva/img/imperva-logo.svg"
    },
    {
        "slug": "imperva_cloud_waf",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/imperva_cloud_waf/img/imperva-logo.svg"
    },
    {
        "slug": "influxdb",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/influxdb/img/influxdb-logo.svg"
    },
    {
        "slug": "infoblox_bloxone_ddi",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/infoblox_bloxone_ddi/img/infoblox-bloxone-ddi-logo.svg"
    },
    {
        "slug": "infoblox_nios",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/infoblox_nios/img/infoblox-logo.svg"
    },
    {
        "slug": "infoblox_threat_defense",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/infoblox_threat_defense/img/infoblox-threat-defense-logo.svg"
    },
    {
        "slug": "iptables",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/iptables/img/linux.svg"
    },
    {
        "slug": "island_browser",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/island_browser/img/island-browser-logo.svg"
    },
    {
        "slug": "istio",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/istio/img/logo_istio.svg"
    },
    {
        "slug": "jamf_compliance_reporter",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/jamf_compliance_reporter/img/jamf-compliance-reporter-logo.svg"
    },
    {
        "slug": "jamf_pro",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/jamf_pro/img/logo.png"
    },
    {
        "slug": "jamf_protect",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/jamf_protect/img/jamf_logo.svg"
    },
    {
        "slug": "jira",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/elastic_connectors/img/service_type/jira.svg"
    },
    {
        "slug": "jolokia_input",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/jolokia_input/img/jolokia_logo.svg"
    },
    {
        "slug": "journald",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/journald/img/systemd-logo.svg"
    },
    {
        "slug": "jumpcloud",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/jumpcloud/img/jumpcloud.svg"
    },
    {
        "slug": "juniper_junos",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/juniper_junos/img/logo.svg"
    },
    {
        "slug": "juniper_netscreen",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/juniper_netscreen/img/logo.svg"
    },
    {
        "slug": "juniper_srx",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/juniper_srx/img/logo.svg"
    },
    {
        "slug": "kafka",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/kafka/img/logo_kafka.svg"
    },
    {
        "slug": "kafka_log",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/kafka_log/img/logo_kafka.svg"
    },
    {
        "slug": "keeper_security_siem_integration",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/keeper_security_siem_integration/img/keeper-logo.svg"
    },
    {
        "slug": "keycloak",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/keycloak/img/keycloak-logo.svg"
    },
    {
        "slug": "kibana",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/kibana/img/logo_kibana.svg"
    },
    {
        "slug": "kubernetes",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/kubernetes/img/logo_kubernetes.svg"
    },
    {
        "slug": "kubernetes_otel",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/kubernetes_otel/img/kubernetes-otel-logo.svg"
    },
    {
        "slug": "lastpass",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/lastpass/img/lastpass-logo.svg"
    },
    {
        "slug": "linux",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/linux/img/metricbeat-services-host.png"
    },
    {
        "slug": "lmd",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/lmd/img/icon-machine-learning.svg"
    },
    {
        "slug": "log",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/log/img/icon.svg"
    },
    {
        "slug": "logstash",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/logstash/img/logo_logstash.svg"
    },
    {
        "slug": "lumos",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/lumos/img/lumos-logo.svg"
    },
    {
        "slug": "lyve_cloud",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/lyve_cloud/img/LyveCloud-Logo.svg"
    },
    {
        "slug": "m365_defender",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/m365_defender/img/logo.svg"
    },
    {
        "slug": "mattermost",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/mattermost/img/mattermost-logo.svg"
    },
    {
        "slug": "memcached",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/memcached/img/logo_memcached.svg"
    },
    {
        "slug": "menlo",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/menlo/img/logo.png"
    },
    {
        "slug": "microsoft_defender_cloud",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/microsoft_defender_cloud/img/microsoft-defender-cloud-logo.svg"
    },
    {
        "slug": "microsoft_defender_endpoint",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/microsoft_defender_endpoint/img/logo.svg"
    },
    {
        "slug": "microsoft_dhcp",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/microsoft_dhcp/img/logo.svg"
    },
    {
        "slug": "microsoft_dnsserver",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/microsoft_dnsserver/img/logo.svg"
    },
    {
        "slug": "microsoft_exchange_online_message_trace",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/microsoft_exchange_online_message_trace/img/logo.svg"
    },
    {
        "slug": "microsoft_exchange_server",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/microsoft_exchange_server/img/exchange.svg"
    },
    {
        "slug": "microsoft_sentinel",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/microsoft_sentinel/img/microsoft-sentinel-logo.svg"
    },
    {
        "slug": "microsoft_sql",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/elastic_connectors/img/service_type/microsoft_sql.svg"
    },
    {
        "slug": "microsoft_sqlserver",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/microsoft_sqlserver/img/microsoft-sql-server-logo.svg"
    },
    {
        "slug": "mimecast",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/mimecast/img/sample-logo.svg"
    },
    {
        "slug": "miniflux",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/miniflux/img/miniflux-logo.svg"
    },
    {
        "slug": "modsecurity",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/modsecurity/img/modsec.svg"
    },
    {
        "slug": "mongodb",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/mongodb/img/logo_mongodb.svg"
    },
    {
        "slug": "mongodb",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/elastic_connectors/img/service_type/mongodb.svg"
    },
    {
        "slug": "mongodb_atlas",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/mongodb_atlas/img/mongodb_atlas-logo.svg"
    },
    {
        "slug": "mysql",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/mysql/img/logo_mysql.svg"
    },
    {
        "slug": "mysql",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/elastic_connectors/img/service_type/mysql.svg"
    },
    {
        "slug": "mysql_enterprise",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/mysql_enterprise/img/logo_mysql.svg"
    },
    {
        "slug": "mysql_otel",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/mysql_otel/img/logo_mysql_otel.svg"
    },
    {
        "slug": "nagios_xi",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/nagios_xi/img/nagios_xi-logo.svg"
    },
    {
        "slug": "nats",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/nats/img/nats.svg"
    },
    {
        "slug": "neon_cyber",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/neon_cyber/img/neoncyber-logo.svg"
    },
    {
        "slug": "netflow",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/netflow/img/netflow-conversation.png"
    },
    {
        "slug": "netscout",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/netscout/img/logo.svg"
    },
    {
        "slug": "netskope",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/netskope/img/netskope-logo.svg"
    },
    {
        "slug": "network_drive",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/elastic_connectors/img/service_type/network_drive.svg"
    },
    {
        "slug": "nginx",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/nginx/img/logo_nginx.svg"
    },
    {
        "slug": "nginx_ingress_controller",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/nginx_ingress_controller/img/logo_nginx.svg"
    },
    {
        "slug": "nginx_ingress_controller_otel",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/nginx_ingress_controller_otel/img/logo_nginx.svg"
    },
    {
        "slug": "nginx_otel",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/nginx_otel/img/logo_nginx.svg"
    },
    {
        "slug": "notion",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/elastic_connectors/img/service_type/notion.svg"
    },
    {
        "slug": "nozomi_networks",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/nozomi_networks/img/nozomi_networks-logo.svg"
    },
    {
        "slug": "nvidia_gpu",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/nvidia_gpu/img/nvidia_logo.svg"
    },
    {
        "slug": "o365",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/o365/img/logo-integrations-microsoft-365.svg"
    },
    {
        "slug": "o365_metrics",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/o365_metrics/img/logo-integrations-microsoft-365.svg"
    },
    {
        "slug": "okta",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/okta/img/okta-logo.svg"
    },
    {
        "slug": "onedrive",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/elastic_connectors/img/service_type/onedrive.svg"
    },
    {
        "slug": "openai",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/openai/img/openai-logo.svg"
    },
    {
        "slug": "opencanary",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/opencanary/img/logo.svg"
    },
    {
        "slug": "oracle",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/oracle/img/oracle_logo.svg"
    },
    {
        "slug": "oracle",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/elastic_connectors/img/service_type/oracle.svg"
    },
    {
        "slug": "oracle_weblogic",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/oracle_weblogic/img/oracle_weblogic-logo.svg"
    },
    {
        "slug": "osquery",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/osquery/img/logo_osquery.svg"
    },
    {
        "slug": "osquery_manager",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/osquery_manager/img/logo_osquery.svg"
    },
    {
        "slug": "outlook",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/elastic_connectors/img/service_type/outlook.svg"
    },
    {
        "slug": "pad",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/pad/img/icon-machine-learning.svg"
    },
    {
        "slug": "panw",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/panw/img/logo-integrations-paloalto-networks.svg"
    },
    {
        "slug": "panw_cortex_xdr",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/panw_cortex_xdr/img/icon-cortex.svg"
    },
    {
        "slug": "panw_metrics",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/panw_metrics/img/logo.svg"
    },
    {
        "slug": "pfsense",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/pfsense/img/pfsense.svg"
    },
    {
        "slug": "php_fpm",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/php_fpm/img/php_fpm-logo.svg"
    },
    {
        "slug": "ping_federate",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/ping_federate/img/ping_federate-logo.svg"
    },
    {
        "slug": "ping_one",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/ping_one/img/ping-one-logo.svg"
    },
    {
        "slug": "platform_observability",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/platform_observability/img/logo_kibana.svg"
    },
    {
        "slug": "postgresql",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/postgresql/img/logo_postgres.svg"
    },
    {
        "slug": "postgresql",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/elastic_connectors/img/service_type/postgresql.svg"
    },
    {
        "slug": "postgresql_otel",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/postgresql_otel/img/otel_postgresql.svg"
    },
    {
        "slug": "pps",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/pps/img/logo.svg"
    },
    {
        "slug": "prisma_access",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/prisma_access/img/prisma-access-logo.svg"
    },
    {
        "slug": "prisma_cloud",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/prisma_cloud/img/prisma_cloud-logo.svg"
    },
    {
        "slug": "problemchild",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/problemchild/img/icon-machine-learning.svg"
    },
    {
        "slug": "prometheus",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/prometheus/img/logo_prometheus.svg"
    },
    {
        "slug": "prometheus_input",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/prometheus_input/img/logo_prometheus.svg"
    },
    {
        "slug": "proofpoint_itm",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/proofpoint_itm/img/proofpoint_itm-logo.svg"
    },
    {
        "slug": "proofpoint_on_demand",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/proofpoint_on_demand/img/proofpoint_on_demand-logo.svg"
    },
    {
        "slug": "proofpoint_tap",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/proofpoint_tap/img/proofpoint_tap-logo.svg"
    },
    {
        "slug": "proxysg",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/proxysg/img/proxysg_logo.svg"
    },
    {
        "slug": "pulse_connect_secure",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/pulse_connect_secure/img/pulse_connect_secure.svg"
    },
    {
        "slug": "qnap_nas",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/qnap_nas/img/logo.svg"
    },
    {
        "slug": "qualys_gav",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/qualys_gav/img/qualys_gav-logo.svg"
    },
    {
        "slug": "qualys_vmdr",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/qualys_vmdr/img/qualys-vmdr-logo.svg"
    },
    {
        "slug": "qualys_was",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/qualys_was/img/qualys-was-logo.svg"
    },
    {
        "slug": "rabbitmq",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/rabbitmq/img/logo_rabbitmq.svg"
    },
    {
        "slug": "radware",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/radware/img/logo.svg"
    },
    {
        "slug": "rapid7_insightvm",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/rapid7_insightvm/img/rapid7-insightvm-logo.svg"
    },
    {
        "slug": "redis",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/redis/img/logo_redis.svg"
    },
    {
        "slug": "redisenterprise",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/redisenterprise/img/logo_redis.svg"
    },
    {
        "slug": "rubrik",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/rubrik/img/rubrik-logo.svg"
    },
    {
        "slug": "sailpoint_identity_sc",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/sailpoint_identity_sc/img/sics.svg"
    },
    {
        "slug": "salesforce",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/salesforce/img/salesforce.svg"
    },
    {
        "slug": "salesforce",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/elastic_connectors/img/service_type/salesforce.svg"
    },
    {
        "slug": "sandfly",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/elastic_connectors/img/service_type/sandfly.svg"
    },
    {
        "slug": "santa",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/santa/img/icon.svg"
    },
    {
        "slug": "security_ai_prompts",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/security_ai_prompts/img/security-logo-color-64px.svg"
    },
    {
        "slug": "security_detection_engine",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/security_detection_engine/img/security-logo-color-64px.svg"
    },
    {
        "slug": "sentinel_one",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/sentinel_one/img/sentinel-one-logo.svg"
    },
    {
        "slug": "sentinel_one_cloud_funnel",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/sentinel_one_cloud_funnel/img/sentinel-one-cloud-funnel-logo.svg"
    },
    {
        "slug": "servicenow",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/servicenow/img/servicenow-logo.svg"
    },
    {
        "slug": "servicenow",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/elastic_connectors/img/service_type/servicenow.svg"
    },
    {
        "slug": "sharepoint_online",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/elastic_connectors/img/service_type/sharepoint_online.svg"
    },
    {
        "slug": "sharepoint_server",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/elastic_connectors/img/service_type/sharepoint_server.svg"
    },
    {
        "slug": "slack",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/slack/img/slack.svg"
    },
    {
        "slug": "slack",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/elastic_connectors/img/service_type/slack.svg"
    },
    {
        "slug": "snort",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/snort/img/snort.svg"
    },
    {
        "slug": "snyk",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/snyk/img/snyk-logo.svg"
    },
    {
        "slug": "sonicwall_firewall",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/sonicwall_firewall/img/logo.svg"
    },
    {
        "slug": "sophos",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/sophos/img/logo.svg"
    },
    {
        "slug": "sophos_central",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/sophos_central/img/sophos_central_logo.svg"
    },
    {
        "slug": "splunk",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/splunk/img/splunk-logo.svg"
    },
    {
        "slug": "spring_boot",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/spring_boot/img/spring_boot-logo.svg"
    },
    {
        "slug": "spycloud",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/spycloud/img/spycloud-logo.svg"
    },
    {
        "slug": "sql_input",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/sql_input/img/sql-server-icon.svg"
    },
    {
        "slug": "squid",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/squid/img/squid-logo.png"
    },
    {
        "slug": "stan",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/stan/img/stan.svg"
    },
    {
        "slug": "statsd_input",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/statsd_input/img/statsd.svg"
    },
    {
        "slug": "stormshield",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/stormshield/img/stormshield_logo.png"
    },
    {
        "slug": "sublime_security",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/sublime_security/img/sublime_security-dark.svg"
    },
    {
        "slug": "suricata",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/suricata/img/suricata.svg"
    },
    {
        "slug": "swimlane",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/swimlane/img/swimlane.png"
    },
    {
        "slug": "symantec_endpoint",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/symantec_endpoint/img/logo.svg"
    },
    {
        "slug": "symantec_endpoint_security",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/symantec_endpoint_security/img/symantec-logo.svg"
    },
    {
        "slug": "synthetics",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/synthetics/img/uptime-logo-color-64px.svg"
    },
    {
        "slug": "synthetics_dashboards",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/synthetics_dashboards/img/uptime-logo-color-64px.svg"
    },
    {
        "slug": "sysdig",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/sysdig/img/sysdig-logo-badge.svg"
    },
    {
        "slug": "syslog_router",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/syslog_router/img/icon.svg"
    },
    {
        "slug": "sysmon_linux",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/sysmon_linux/img/sysmon-linux.svg"
    },
    {
        "slug": "system",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/system/img/system.svg"
    },
    {
        "slug": "system_audit",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/system_audit/img/system-audit-overview-dashboard.png"
    },
    {
        "slug": "system_otel",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/system_otel/img/system-otel.svg"
    },
    {
        "slug": "tanium",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/tanium/img/tanium-logo.svg"
    },
    {
        "slug": "tcp",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/tcp/img/icon.svg"
    },
    {
        "slug": "teams",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/elastic_connectors/img/service_type/teams.svg"
    },
    {
        "slug": "teleport",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/teleport/img/teleport-logo.svg"
    },
    {
        "slug": "tenable_io",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/tenable_io/img/tenable_io-logo.svg"
    },
    {
        "slug": "tenable_ot_security",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/tenable_ot_security/img/logo.svg"
    },
    {
        "slug": "tenable_sc",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/tenable_sc/img/tenable_sc-logo.svg"
    },
    {
        "slug": "tencent_cloud",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/tencent_cloud/img/logo.png"
    },
    {
        "slug": "tetragon",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/tetragon/img/logo.svg"
    },
    {
        "slug": "threat_map",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/threat_map/img/sample-logo.svg"
    },
    {
        "slug": "thycotic_ss",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/thycotic_ss/img/thycotic.svg"
    },
    {
        "slug": "ti_abusech",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/ti_abusech/img/abusech2.svg"
    },
    {
        "slug": "ti_anomali",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/ti_anomali/img/anomali.svg"
    },
    {
        "slug": "ti_cif3",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/ti_cif3/img/csg_logo_big.svg"
    },
    {
        "slug": "ti_crowdstrike",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/ti_crowdstrike/img/crowdstrike_falcon_intelligence-logo.svg"
    },
    {
        "slug": "ti_custom",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/ti_custom/img/stix-logo.png"
    },
    {
        "slug": "ti_cybersixgill",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/ti_cybersixgill/img/cybersixgill.svg"
    },
    {
        "slug": "ti_cyware_intel_exchange",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/ti_cyware_intel_exchange/img/cyware_logo.svg"
    },
    {
        "slug": "ti_domaintools",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/ti_domaintools/img/logo.png"
    },
    {
        "slug": "ti_eclecticiq",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/ti_eclecticiq/img/logo_RGB.svg"
    },
    {
        "slug": "ti_eset",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/ti_eset/img/eset-lozenge-color-rgb.svg"
    },
    {
        "slug": "ti_google_threat_intelligence",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/ti_google_threat_intelligence/img/ti_google_threat_intelligence-logo.png"
    },
    {
        "slug": "ti_greynoise",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/ti_greynoise/img/greynoise_logo.jpeg"
    },
    {
        "slug": "ti_maltiverse",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/ti_maltiverse/img/logo-maltiverse.svg"
    },
    {
        "slug": "ti_mandiant_advantage",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/ti_mandiant_advantage/img/mandiant-logo.svg"
    },
    {
        "slug": "ti_misp",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/ti_misp/img/misp.svg"
    },
    {
        "slug": "ti_opencti",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/ti_opencti/img/opencti-logo.svg"
    },
    {
        "slug": "ti_otx",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/ti_otx/img/otx.svg"
    },
    {
        "slug": "ti_rapid7_threat_command",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/ti_rapid7_threat_command/img/ti_rapid7_threat_command-logo.svg"
    },
    {
        "slug": "ti_recordedfuture",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/ti_recordedfuture/img/logo.svg"
    },
    {
        "slug": "ti_threatconnect",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/ti_threatconnect/img/threat-connect-logo.svg"
    },
    {
        "slug": "ti_threatq",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/ti_threatq/img/threatq.svg"
    },
    {
        "slug": "ti_util",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/ti_util/img/security-logo-color-64px.svg"
    },
    {
        "slug": "tines",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/tines/img/tines-purple-logo.png"
    },
    {
        "slug": "tomcat",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/tomcat/img/logo.svg"
    },
    {
        "slug": "traefik",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/traefik/img/traefik.svg"
    },
    {
        "slug": "trellix_edr_cloud",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/trellix_edr_cloud/img/trellix-edr-cloud-logo.svg"
    },
    {
        "slug": "trellix_epo_cloud",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/trellix_epo_cloud/img/trellix-logo.svg"
    },
    {
        "slug": "trend_micro_vision_one",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/trend_micro_vision_one/img/trend-micro-vision-one-logo.svg"
    },
    {
        "slug": "trendmicro",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/trendmicro/img/trend-micro-logo.svg"
    },
    {
        "slug": "tychon",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/tychon/img/TychonLogo.svg"
    },
    {
        "slug": "udp",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/udp/img/icon.svg"
    },
    {
        "slug": "unifiedlogs",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/unifiedlogs/img/logo_macos.svg"
    },
    {
        "slug": "universal_profiling_agent",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/universal_profiling_agent/img/profiler-logo-color-48px.svg"
    },
    {
        "slug": "universal_profiling_collector",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/universal_profiling_collector/img/profiler-logo-color-48px.svg"
    },
    {
        "slug": "universal_profiling_symbolizer",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/universal_profiling_symbolizer/img/profiler-logo-color-48px.svg"
    },
    {
        "slug": "varonis",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/varonis/img/sample-logo.svg"
    },
    {
        "slug": "vectra_detect",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/vectra_detect/img/vectra-logo.svg"
    },
    {
        "slug": "vectra_rux",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/vectra_rux/img/vectra_rux-logo.svg"
    },
    {
        "slug": "vsphere",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/vsphere/img/vmware.svg"
    },
    {
        "slug": "watchguard_firebox",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/watchguard_firebox/img/watchguard-logo.svg"
    },
    {
        "slug": "websocket",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/websocket/img/websocket_configuration.png"
    },
    {
        "slug": "websphere_application_server",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/websphere_application_server/img/websphere_application_server-logo.svg"
    },
    {
        "slug": "windows",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/windows/img/logo_windows.svg"
    },
    {
        "slug": "windows_etw",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/windows_etw/img/logo_windows.svg"
    },
    {
        "slug": "winlog",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/winlog/img/logo_windows.svg"
    },
    {
        "slug": "wiz",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/wiz/img/wiz-logo.svg"
    },
    {
        "slug": "wmi",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/wmi/img/logo_windows.svg"
    },
    {
        "slug": "zeek",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/zeek/img/zeek.svg"
    },
    {
        "slug": "zerofox",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/zerofox/img/logo.svg"
    },
    {
        "slug": "zeronetworks",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/zeronetworks/img/logo.svg"
    },
    {
        "slug": "zookeeper",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/zookeeper/img/zookeeper.svg"
    },
    {
        "slug": "zoom",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/zoom/img/zoom_blue.svg"
    },
    {
        "slug": "zoom",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/elastic_connectors/img/service_type/zoom.svg"
    },
    {
        "slug": "zscaler_zia",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/zscaler_zia/img/zscaler-logo.svg"
    },
    {
        "slug": "zscaler_zpa",
        "logo": "https://raw.githubusercontent.com/elastic/integrations/main/packages/zscaler_zpa/img/zscaler-logo.svg"
    }
  ];
  
  export default logos;
